baseURL = 'https://xiaofengsoft.github.io/'
languageCode = 'zh-CN'
languageName = '中文'
title = '张一风的博客'
theme = 'hugo-coder'


[pagination]
pagerSize = 20

[services]
[services.disqus]
shortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  author = "张一风"
  info = "全栈开发与模型训练"
  description = "张一风的个人网站"
  keywords = "博客,开发者,个人"
  avatarurl = "https://q1.qlogo.cn/g?b=qq&nk=1365038232&s=640"
  #gravatar = "xiaofengs@yeah.net"

  faviconSVG = "https://q1.qlogo.cn/g?b=qq&nk=1365038232&s=640"
  favicon_32 = "https://q1.qlogo.cn/g?b=qq&nk=1365038232&s=640"
  favicon_16 = "https://q1.qlogo.cn/g?b=qq&nk=1365038232&s=640"

  since = 2023

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

  math = true # Enable math rendering

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/xiaofengsoft"

[[params.social]]
  name = "Twitter"
  icon = "fa-brands fa-x-twitter fa-2x"
  weight = 3
  url = "https://x.com/xiaofengsxf"

# Menu links

[[menu.main]]
  name = "关于"
  weight = 1
  url = "intro"
[[menu.main]]
  name = "解决办法"
  url = "解决办法/"
  weight = 2
[[menu.main]]
  name = "编程语言"
  url = "编程语言/"
  weight = 3
[[menu.main]]
  name = "数学"
  url = "数学/"
  weight = 4
[[menu.main]]
  name = "题解"
  url = "题解/"
  weight = 5
[[menu.main]]
  name = "人工智能"
  url = "人工智能/"
  weight = 6


[params.giscus] # https://giscus.app
  repo = "xiaofengsoft/xiaofengsoft.github.io"
  repoID = "R_kgDOOxbv5w"
  category = "General"
  categoryID = "DIC_kwDOOxbv584CqrKG"
  mapping = "pathname"
  term = ""
  strict = "0"
  reactionsEnabled = "1"
  emitMetadata = "0"
  inputPosition = "bottom"
  theme = "preferred_color_scheme"
  lang = "zh-CN"
  loading = ""

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]

          
